# Generated by Django 5.0.6 on 2024-07-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_comment_options_alter_comment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='author',
        ),
    ]
