# Generated by Django 5.0.6 on 2024-07-21 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_creator_task_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['likes', '-created_at']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='task',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('comment', 'author')},
        ),
    ]
